# Generated by Django 4.0.1 on 2022-01-22 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('ma', 'male'), ('fe', 'female')], default='ma', max_length=2)),
                ('business_account', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='store_image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='store_image/')),
                ('about_text', models.TextField(blank=True, max_length=500, null=True)),
                ('alt_text', models.TextField(blank=True, max_length=500, null=True)),
                ('creation_date', models.DateTimeField()),
                ('destination_link', models.URLField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='base.account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.account')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('Pronouns', models.CharField(choices=[('he', 'he/him'), ('hr', 'she/her'), ('ty', 'they/them')], default='he', max_length=2)),
                ('website', models.URLField(max_length=100)),
                ('short_bio', models.TextField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, default='', null=True, upload_to='store_image/')),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pin', to='base.account')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_pin', to='base.pin')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_pin', to='base.pin')),
                ('reporter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='base.account')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_account', to='base.account')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like', to='base.pin')),
            ],
        ),
        migrations.CreateModel(
            name='FollowHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='base.account')),
                ('following_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='base.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=255)),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 15, 29, 41, 739835))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='base.account')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='base.pin')),
            ],
        ),
    ]
