# Generated by Django 4.0.1 on 2022-01-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_profile_followers_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 20, 18, 47, 321688)),
        ),
    ]
