# Generated by Django 4.0.1 on 2022-01-23 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_pin_comments_count_pin_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='Pronouns',
            field=models.CharField(blank=True, choices=[('he', 'he/him'), ('hr', 'she/her'), ('ty', 'they/them')], default='he', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='store_image/'),
        ),
        migrations.AddField(
            model_name='account',
            name='short_bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 10, 21, 30, 214998)),
        ),
        migrations.AlterField(
            model_name='followhandle',
            name='follower_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_acc', to='base.account'),
        ),
        migrations.AlterField(
            model_name='followhandle',
            name='following_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_acc', to='base.account'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
