# Generated by Django 4.0.1 on 2022-01-23 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_account_gender_account_pronouns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 24, 55, 200684)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
