# Generated by Django 4.0.1 on 2022-01-24 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 10, 30, 6, 107263)),
        ),
    ]
