# Generated by Django 4.0.1 on 2022-01-24 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Pronouns',
            field=models.CharField(blank=True, choices=[('he', 'he/him'), ('she', 'she/her'), ('they', 'they/them')], default='he', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 15, 36, 22, 499787)),
        ),
    ]
