# Generated by Django 4.0.1 on 2022-01-26 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 11, 58, 0, 787420)),
        ),
    ]
