# Generated by Django 4.0.1 on 2022-01-26 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_followhandle_follower_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 0, 32, 6, 123438)),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image/'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
