# Generated by Django 4.0.1 on 2022-01-27 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_account_user_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 11, 43, 35, 508860)),
        ),
    ]
