# Generated by Django 4.0.1 on 2022-01-29 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_account_options_comment_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 15, 19, 47, 69033)),
        ),
    ]
