# Generated by Django 4.0.1 on 2022-01-31 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_comment_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='followhandle',
            name='follower_user',
        ),
        migrations.RemoveField(
            model_name='followhandle',
            name='following_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 11, 53, 17, 172163)),
        ),
        migrations.AlterField(
            model_name='followhandle',
            name='follower_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_account', to='base.account'),
        ),
        migrations.AlterField(
            model_name='followhandle',
            name='following_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings_account', to='base.account'),
        ),
    ]
