# Generated by Django 4.0.1 on 2022-01-31 16:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_account_user_name_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='username must be english', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 20, 28, 3, 793207)),
        ),
    ]
