# Generated by Django 4.0.1 on 2022-01-31 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_account_user_alter_comment_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password',
            new_name='passwordd',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 21, 59, 24, 117711)),
        ),
    ]
