# Generated by Django 4.0.1 on 2022-02-01 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 14, 59, 24, 925958)),
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen', to='base.account')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_pin', to='base.pin')),
            ],
        ),
    ]
