# Generated by Django 4.0.1 on 2022-02-01 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_comment_comment_date_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 15, 8, 18, 396082)),
        ),
    ]
