# Generated by Django 4.0.1 on 2022-02-01 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 15, 19, 27, 107372)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='base.pin'),
        ),
    ]
