# Generated by Django 4.0.1 on 2022-02-03 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_comment_comment_date_alter_comment_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='seens_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 9, 58, 34, 411092)),
        ),
    ]
